name: flutter_app
description: "玄学命理"
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  shared_preferences: ^2.3.4
  flutter_markdown: ^0.7.7
  provider: ^6.1.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
